#!/usr/bin/bash

if [ -f .env ]; then
	export $(cat .env | xargs)
else
	test -z "$MODE" && MODE=1
	test -z "$PARANOID" && PARANOID=0
	test -z "$QUICK" && QUICK=0
fi

set -e
shopt -s extglob

FOLDER=$1
TARGETS=(${@:2})
[ -z "$FOLDER" ] && exit
[ -z "$TARGETS" ] && exit
test "$QUICK" = "0" && CAT="glow -" || CAT="tee"

function first-level-chunks() {
	# CHUNK_SIZE First Level Elements Per Chunk
	CHUNK_SIZE=4
	EMAIL=$(whatismyemail)

	for((i=0; i < ${#TARGETS[@]}; i+=CHUNK_SIZE))
	do
		CHUNK=("${TARGETS[@]:i:CHUNK_SIZE}")
		echo "Starting encryption on chunk N#$i. Elements in this group: ${CHUNK[*]}" | $CAT
		if [ $PARANOID -eq 1 ]; then
			KN=$((i % 5 + 1))
			echo "Using paranoid mode and key N#$KN" | $CAT
			gpg-encrypt-folder "$FOLDER+$i" "K$KN" "$QUICK" ${CHUNK[*]}
		else
			gpg-encrypt-folder "$FOLDER+$i" "$EMAIL" "$QUICK" ${CHUNK[*]}
		fi
	done
}

function file-count-chunks() {
	# CHUNK_SIZE Files Per Chunk
        CHUNK_SIZE=512
	EMAIL=$(whatismyemail)

	RECU_TARGETS=($(find ${TARGETS[*]} -type f -not -name ".env"))
        for((i=0; i < ${#RECU_TARGETS[@]}; i+=CHUNK_SIZE))
        do
                CHUNK=("${RECU_TARGETS[@]:i:CHUNK_SIZE}")
                echo "Starting encryption on chunk N#$i. Elements in this group: n.${#CHUNK[@]}" | $CAT
		if [ $PARANOID -eq 1 ]; then
			KN=$((i % 5 + 1))
			echo "Using paranoid mode and key N#$KN" | $CAT
			gpg-encrypt-folder "$FOLDER+$i" "K$KN" "$QUICK" ${CHUNK[*]}
		else
                	gpg-encrypt-folder "$FOLDER+$i" "$EMAIL" "$QUICK" ${CHUNK[*]}
		fi
		# Remove Empty Folders As To Not Leak The Folder Structure
		echo ${TARGETS[*]} | while read f; do
			dirname $f
		done | uniq | xargs -I{} find "{}" -type d -empty -delete
        done
}

function file-size-chunks() {
	# CHUNK_SIZE Bytes Per Chunk
	CHUNK_SIZE=200000	# ~200M
	EMAIL=$(whatismyemail)

	RECU_TARGETS=($(find ${TARGETS[*]} -type f -not -name ".env"))
	while true
	do
		CHUNK=()
		i=0
		for f in ${RECU_TARGETS[*]}; do
			(( i+=1 ))
			if [ ! -f $f ]; then
				continue
			fi
			CHUNK+=($f)
			S=$(du -c ${CHUNK[*]:-/dev/null} | tail -n1 | awk '{print $1}')
			if (( $S >= $CHUNK_SIZE )); then
				break
			fi
		done
		if [ "${CHUNK[*]}" == "" ]; then
			break
		fi
		echo "Starting encryption on chunk N#$i. Chunk size: $S" | $CAT
		if [ $PARANOID -eq 1 ]; then
			KN=$((i % 5 + 1))
			echo "Using paranoid mode and key N#$KN" | $CAT
			gpg-encrypt-folder "$FOLDER+$i" "K$KN" "$QUICK" ${CHUNK[*]}
		else
			gpg-encrypt-folder "$FOLDER+$i" "$EMAIL" "$QUICK" ${CHUNK[*]}
		fi
		# Remove Empty Folders As To Not Leak The Folder Structure
		echo ${TARGETS[*]} | while read f; do
			dirname $f
		done | uniq | xargs -I{} find "{}" -type d -empty -delete
	done
}

test $MODE == 1 && first-level-chunks
test $MODE == 2 && file-count-chunks
test $MODE == 3 && file-size-chunks
shopt -u extglob
