#!/usr/bin/bash

set -e
shopt -s extglob

FOLDER=$1
[ -z "$FOLDER" ] && exit

find $FOLDER+* -maxdepth 1 | while read f; do
	echo "Starting decryption on chunk $f" | glow -
	gpg-decrypt-folder "$(basename $f .tar.gz.gpg)"
done
shopt -u extglob
