#!/usr/bin/bash

set -e

EMAIL=$2
FOLDER=$1
QUICK=$3
TARGETS=${@:4}
[ -z "$FOLDER" ] && exit
[ -z "$TARGETS" ] && exit
[ "$QUICK" = "0" ] && BAR="pv" || BAR="tee"

shopt -s extglob
export GPG_TTY=$(tty)

echo "Using *gzip + tar* utilities to compress the selected targets into **$FOLDER.tar.gz**" | glow -

SIZE=$(printf '%q' $TARGETS | du -sbc | tail -n1 | awk '{print $1}')
[ "$QUICK" -eq "0" ] && tar czf - $TARGETS -P | pv -s $SIZE | gzip > $FOLDER.tar.gz || tar czf - $TARGETS -P | gzip > $FOLDER.tar.gz

echo "Using *gpg* utility to encrypt the archive **$FOLDER.tar.gz** using recipient email **$EMAIL**" | glow -

$BAR < $FOLDER.tar.gz | gpg --trust-model always -q -e --recipient "$EMAIL" - > $FOLDER.tar.gz.gpg

echo "Removing unnecessary files" | glow -

rm -fv $TARGETS $FOLDER.tar.gz
shopt -u extglob
