#!/usr/bin/bash

set -e
shopt -s extglob

FOLDER=$1
PASSWD=$2
QUICK=$3
[ -z "$FOLDER" ] && exit
test "$QUICK" = "0" && BAR="pv" || BAR="tee"
test "$QUICK" = "0" && CAT="glow -" || CAT="tee"

echo "Using *gpg* utility to decrypt the archive **$FOLDER**" | $CAT

if [ -z "$PASSWD" ]; then
	$BAR < $FOLDER.tar.gz.gpg | gpg --trust-model always -q -d - > $FOLDER.tar.gz
else
	$BAR < $FOLDER.tar.gz.gpg | gpg --batch --yes --pinentry-mode loopback --passphrase "$PASSWD" --trust-model always -q -d - > $FOLDER.tar.gz
fi
# echo -n "Tar Size: "
# du -h $FOLDER.tar.gz | tail -n1 | awk '{print $1}'

echo "Using *gzip + tar* utilities to decompress archive **$FOLDER.tar.gz**" | $CAT

$BAR < $FOLDER.tar.gz | gzip -d - > $FOLDER.tar
$BAR < $FOLDER.tar | tar xzf -

echo "Removing unnecessary files" | $CAT

rm -fv $FOLDER.tar*
shopt -u extglob
