#!/usr/bin/bash

set -e
shopt -s extglob

FOLDER=$1
[ -z "$FOLDER" ] && exit

echo "Using *gpg* utility to decrypt the archive **$FOLDER.tar.gz.gpg**" | glow -

pv < $FOLDER.tar.gz.gpg | gpg --trust-model always -q -d - > $FOLDER.tar.gz
# echo -n "Tar Size: "
# du -h $FOLDER.tar.gz | tail -n1 | awk '{print $1}'

echo "Using *gzip + tar* utilities to decompress archive **$FOLDER.tar.gz**" | glow -

pv < $FOLDER.tar.gz | gzip -d - > $FOLDER.tar
pv < $FOLDER.tar | tar xzf -

echo "Removing unnecessary files" | glow -

rm -fv $FOLDER.tar* | pv -l -s $(du -a $FOLDER.tar* | wc -l) > /dev/null
shopt -u extglob
