#!/usr/bin/bash

mkdir $HOME/.notifications 2> /dev/null
inotifywait -mr \
  --timefmt '%d/%m/%y %H:%M' --format '%T %w %f' -e close_write $HOME/.notifications |
while read -r date time dir file; do
	app=$(cat $dir$file | head -n1)
	title=$(cat $dir$file | head -n2 | tail -n1)
	text=$(cat $dir$file | tail -n1)
	echo -e "\n[*$date* *$time*] (**$app**)\n# $title\n> $text\n" | glow -
done &
